export default [
  {
    id: 1,
    title: 'Intro',
    duration: 34,
    coverFile: 'freshmen_adjustment.png',
    artist: 'Kanye West',
    album: 'Freshmen Adjustment',
  },
  {
    title: "Livin' In A Movie",
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 207,
    id: 2,
  },
  {
    id: 3,
    title: 'Asian Hooker',
    duration: 242,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    id: 4,
    title: 'Doing Fine',
    duration: 168,
    coverFile: 'freshmen_adjustment.png',
    artist: 'Kanye West',
    album: 'Freshmen Adjustment',
  },
  {
    title: 'Dark Fantasy',
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 312,
    id: 5,
  },
  {
    id: 6,
    title: 'Community Property',
    duration: 219,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    id: 7,
    title: 'Doing Fine',
    duration: 168,
    coverFile: 'freshmen_adjustment.png',
    artist: 'Kanye West',
    album: 'Freshmen Adjustment',
  },
  {
    title: 'All of the Lights',
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 174,
    id: 8,
  },
  {
    id: 9,
    title: 'Self Conscious (a.k.a. Yeah)',
    duration: 215,
    coverFile: 'freshmen_adjustment.png',
    artist: 'Kanye West',
    album: 'Freshmen Adjustment',
  },
  {
    id: 10,
    title: 'Turn Out The Lights',
    duration: 264,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    title: 'So Appalled',
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 231,
    id: 11,
  },
  {
    id: 12,
    title: 'The Shocker',
    duration: 250,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    id: 13,
    title: 'Eyes Of A Panther',
    duration: 217,
    coverFile: 'feel_the_steel.png',
    artist: 'Kanye West',
    album: 'Unreleased',
  },
  {
    id: 14,
    title: "Eatin' Ain't Cheatin'",
    duration: 230,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    title: 'Devil in a New Dress',
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 291,
    id: 15,
  },
  {
    id: 16,
    title: 'The Shocker',
    duration: 250,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    id: 17,
    title: 'Fat Girl (Thar She Blows)',
    duration: 278,
    coverFile: 'feel_the_steel.png',
    artist: 'Kanye West',
    album: 'Unreleased',
  },
  {
    id: 18,
    title: 'Girl From Oklahoma',
    duration: 237,
    coverFile: 'feel_the_steel.png',
    artist: 'Steel Panther',
    album: 'Feel the Steel',
  },
  {
    title: 'Runaway',
    coverFile: 'unreleased.png',
    artist: 'Kanye West',
    album: 'Unreleased',
    duration: 226,
    id: 19,
  },
];

export function formatDuration(seconds) {
  const minutes = Math.floor(seconds / 60);
  const rest = seconds - minutes * 60;
  return `${minutes}:${rest < 10 ? 0 : ''}${rest}`;
}
